kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodeapp
  labels:
    app: nodeapp
    app.kubernetes.io/component: nodeapp
    app.kubernetes.io/instance: nodeapp
    app.kubernetes.io/name: nodeapp
    app.kubernetes.io/part-of: gitops-demo
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-namespace: gh-actions-gitops
spec:
  replicas: {{ .Values.nodeapp.replicas }}
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
        deployment: nodeapp
    spec:
      containers:
        - name: nodeapp
          image: {{ .Values.nodeapp.image }}
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {{ .Values.nodeapp.resources | toYaml | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          env: []
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
              - ALL
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
