kind: Service
apiVersion: v1
metadata:
  name: nodeapp
  labels:
    app: nodeapp
    app.kubernetes.io/component: nodeapp
    app.kubernetes.io/instance: nodeapp
    app.kubernetes.io/name: nodeapp
    app.kubernetes.io/part-of: gitops-demo
    app.openshift.io/runtime-version: latest
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: nodeapp
    deployment: nodeapp
